### ISSUE TITLE
Deps need update to compile with GHC 8.4.4

### ISSUE THREAD

**Issue by Mikolaj** [iconnect/ridley#12]

**Comment by Mikolaj** [comment]
I will bump the deps in both packages and see if there are any apparent crashes in hermes tests. If not, will create PR.

**Comment by Mikolaj** [comment]
@adinapoli: it turns out I need your help here. Could you prod this code a bit and advise me what version of packages that are compatible with GHC 8.4.4 it would best work with? If you happened to solve the problem altogether, I wouldn't mind either. :) 

Ideally I'd have these dependency bumps all the way to newest versions:

```
--- a/ridley-extras/ridley-extras.cabal
+++ b/ridley-extras/ridley-extras.cabal
@@ -23,8 +23,8 @@ library
   exposed-modules:     System.Metrics.Prometheus.Ridley.Metrics.FD
   build-depends:       base >= 4.7 && < 5,
                        text,
-                       prometheus < 0.5.0.0,
-                       shelly < 1.7.0.0,
+                       prometheus < 3,
+                       shelly < 1.9.0.0,
                        microlens,
                        ekg-prometheus-adapter < 0.2.0.0,
                        mtl,
diff --git a/ridley/ridley.cabal b/ridley/ridley.cabal
index 51b01a9..f0fcb93 100644
--- a/ridley/ridley.cabal
+++ b/ridley/ridley.cabal
@@ -32,8 +32,8 @@ library
 
   build-depends:       async < 3.0.0,
                        base >= 4.7 && < 5,
-                       containers < 0.6.0.0,
-                       katip < 0.4.0.0,
+                       containers < 0.7.0.0,
+                       katip < 0.8.0.0,
                        wai-middleware-metrics < 0.3.0.0,
                        template-haskell,
                        ekg-core,
diff --git a/ridley/src/System/Metrics/Prometheus/Ridley.hs b/ridley/src/System/Metrics/Prometheus/Ridley.hs
index 7aa70d3..b80e297 100644
--- a/ridley/src/System/Metrics/Prometheus/Ridley.hs
+++ b/ridley/src/System/Metrics/Prometheus/Ridley.hs
@@ -42,7 +42,7 @@ import           Katip
 import           Lens.Micro
 import           Network.Wai.Metrics (registerWaiMetrics)
 import           System.Metrics as EKG
-import qualified System.Metrics.Prometheus.Concurrent.Http as P
+import qualified System.Metrics.Prometheus.Http.Scrape as P
 import           System.Metrics.Prometheus.Metric.Counter (add)
 import qualified System.Metrics.Prometheus.RegistryT as P
 import           System.Metrics.Prometheus.Ridley.Metrics.CPU
```

but even when I accept the older prometheus-2.0.2 (the alternative older prometheus-0.5.0 conflicts with a lot of packages), I still get into problems (though some may be caused by too new katip), e.g.:

```
    /home/mikolaj/r/ridley/ridley/src/System/Metrics/Prometheus/Ridley.hs:137:44: error:
        • Couldn't match expected type ‘ScribeSettings’
                      with actual type ‘LogEnv -> IO LogEnv’
```

**Comment by Mikolaj** [comment]
@adinapoli: ping :)

**Comment by cdornan** [comment]
@adinapoli we (by which I mean @Mikolaj )  have an update for GHC 8.4.4 which will land here RSN &mdash; can we upload those changes to Hackage (they should work with GHC 7.10 through GHC 8.4).

Will you be able to upload them to Hackage, or better yet, give me and Mikolaj maintainer access to this package on Hackage.

(Hope all is well &mdash; let's catch up some time. 😄)

**Comment by adinapoli** [comment]
@Mikolaj @cdornan Hey folks!

Sorry, my github notifications are on mute for this repo, so even @-mentions weren't getting through -- luckily Mikolaj pinged me on IRC 😉 

Yeah, I think making you guys admin looks like the best option, so that you can fully take control. I have done just that, so you are now both package maintainers for `ridley` and `ridley-extras`:

<img width="951" alt="screenshot 2019-02-06 at 09 08 01" src="https://user-images.githubusercontent.com/442035/52328172-ec01b180-29ee-11e9-8267-e94a35549e24.png">

> (Hope all is well — let's catch up some time. 😄)

Yup, let's make it happen sometimes 😉

**Comment by cdornan** [comment]
great &mdash; thanks @adinapoli 👍

**Comment by Mikolaj** [comment]
@adinapoli: thank you! In that case I will upload new ridley and ridley-extras, if Chris doesn't mind.

**Comment by cdornan** [comment]
Please do @Mikolaj 👍

**Comment by Mikolaj** [comment]
Done. Hackage docs built. Hackage matrix now shows that new GHC's compile the packages fine, though it shows dep failures for GHC 7.10.3, as before --- probably not strict enough bounds. So I've manually tweaked CI `atlas-hermes-710-builder` and verified it builds and tests fine with GHC 7.10.3 and with the new ridley* packages. So, success. Closing.

**Comment by cdornan** [comment]
Great &mdash; thanks @Mikolaj  :+1:
